[colors]
background = '#13140d'
foreground = '#e4e3d7'

cursor_bg = '#bfce7f'
cursor_fg = '#13140d'
cursor_border = '#bfce7f'

selection_bg = '#404c0a'
selection_fg = '#e4e3d7'

ansi = ['#13140d', '#e34a71', '#8ed66e', '#dbb67b', '#86983c', '#919a6b', '#bfce7f', '#abb2bf']
brights = ['#5c6370', '#e05f84', '#a1e086', '#e8c897', '#cddc8f', '#7c7d33', '#6e8046', '#ffffff']
